// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLhRKYQZRbhD53WDj9Y_QGa19nhpmvV-M',
    appId: '1:951900586090:web:7b2434a52a9a15e10d4a13',
    messagingSenderId: '951900586090',
    projectId: 'silentvoice-72166',
    authDomain: 'silentvoice-72166.firebaseapp.com',
    storageBucket: 'silentvoice-72166.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFQqxQikPNgNz165W_GyXyOdOwE5ygxUM',
    appId: '1:951900586090:android:ab8c94ef96b8910a0d4a13',
    messagingSenderId: '951900586090',
    projectId: 'silentvoice-72166',
    storageBucket: 'silentvoice-72166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5NfqKG2H-LMxM0KFSvuMQdaciZsnzglo',
    appId: '1:951900586090:ios:dc0d8aaabba54ceb0d4a13',
    messagingSenderId: '951900586090',
    projectId: 'silentvoice-72166',
    storageBucket: 'silentvoice-72166.firebasestorage.app',
    iosBundleId: 'com.example.silentvoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5NfqKG2H-LMxM0KFSvuMQdaciZsnzglo',
    appId: '1:951900586090:ios:dc0d8aaabba54ceb0d4a13',
    messagingSenderId: '951900586090',
    projectId: 'silentvoice-72166',
    storageBucket: 'silentvoice-72166.firebasestorage.app',
    iosBundleId: 'com.example.silentvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLhRKYQZRbhD53WDj9Y_QGa19nhpmvV-M',
    appId: '1:951900586090:web:8296a924812475800d4a13',
    messagingSenderId: '951900586090',
    projectId: 'silentvoice-72166',
    authDomain: 'silentvoice-72166.firebaseapp.com',
    storageBucket: 'silentvoice-72166.firebasestorage.app',
  );
}
